ControllerSettings:
  boundary_conditions:
    minimum_voltage: 0.95  # Minimum voltage at the grid connection point.
    maximum_voltage: 1.05  # Maximum voltage at the grid connection point.
    price_high: 15  # Minimum temperature in the room.
    price_low: 10  # Maximum temperature in the room.
  actions:
    p_change_for_voltage: 70  # Step size for power setpoint adjustment for voltage correction.
    p_change_for_temperature: 50  # Step size for power setpoint adjustment for temperature correction.
