InitializationSettings:
  config_id: config 1
  configs:
  - storage_capacity: 10000.0
    grid_capacity: 10000000.0
    initial_money: 10.0
    price_high: 0.07
    price_low: 0.01
    add_load: 0.0
    timestep: 60
    plot_port: 1
    plot_car_id: Vehicle#1
